name: 'shop-logbot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,17 * * *'

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: feature/bot

    - name: Install Dependencies
      run: yarn install --frozen-lockfile --no-progress --no-color --emoji=false

    - name: Slack Notification
      run: |
        ls
        echo "self hosted runner current node version: $(node --version)"
        echo ${{ github.workspace }}
        node ${{ github.workspace }}/main.js 
