name: 'shop-logbot'

# on:
#   schedule:
#     - cron: '0 12 * * *'
on:
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: yarn install --frozen-lockfile --no-progress --no-color --emoji=false

    - name: Slack Notification
      run: |
        ls
        echo ${{ github.workspace }}
        echo  $SLACK_BOT_TOKEN
        node ${{ github.workspace }}/main.js 
