name: 'deploy-github-page'

on:
  workflow_dispatch:

jobs:
  deploy-page:
    concurrency: ci-${{ github.ref }} #https://github.com/JamesIves/github-pages-deploy-action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache turbo Test
        uses: actions/cache@v4
        id: test-cache
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - if: steps.test-cache.outputs.cache-hit == 'true'
        run: echo 'test-cache hit'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Deploy page
        run: node page-deploy.js
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
