name: 'deploy-github-page'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  deploy-page:
    concurrency: ci-${{ github.ref }} #https://github.com/JamesIves/github-pages-deploy-action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter=github-action-test-react build
        env:
          PUBLIC_PATH: /${{ github.event.repository.name }}/pr-${{ github.event.number }}/

      - name: Move Pr Folder
        run: |
          mkdir -p pr-${{ github.event.number }}
          mv page/* pr-${{ github.event.number }}
          cp -r pr-${{ github.event.number }} page

      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: page
          clean: true

      - name: Show Page Info
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            > :rocket: Deployed page of ${{ github.event.pull_request.head.sha }}
              https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr/${{ github.event.number }}
