name: 'action-test'

on:
  workflow_dispatch:

jobs:
  file-check:
    name: file Check 
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set timezone
      run: sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

    - name: Set variable
      run: echo "version=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Generate variable text
      run: |
        echo "${{ env.version }}" > container_image_tag.txt

    - name: Check pwd
      run: |
        pwd

    - name: Print List
      run: |
        ls

    - name: Find Tag File
      run: find ~+ -type f -name "*tag.txt"

